ci fix

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,6 +4,9 @@ stages:
   - migrate
   - deploy
 
+before_script:
+  - cp $ENV_FILE .env
+
 build-job:
   stage: build
   script:
@@ -23,8 +26,13 @@ migrate-job:
 deploy-job:
   stage: deploy 
   script:
-    - cp $ENV_FILE .env
     - docker-compose down --remove-orphans
     - docker-compose up -d --build
+    - R_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' alohssh)
+    - if [ "$R_EXIT_CODE" -ne 0 ]; then
+        echo "container failed with exit code $R_EXIT_CODE";
+        docker logs alohssh;
+        exit 1;
+      fi  
     - sleep 5
     - docker-compose logs alohssh
